Feature: Destructive Git commands require confirmation
  A tool_call hook gates destructive Git operations (force push, force
  branch delete, hard reset, clean -f, force worktree remove) with pi's
  native confirm dialog. The gate is not a tool and cannot be skipped: it
  fires at tool-execution time and blocks the call unless the user confirms.

  Background:
    Given the @fradser/git package is installed
    And extensions/risky-gate.ts registers a tool_call hook (no registerTool)

  Scenario: Force push is gated by an option dialog
    When the model runs "git push --force origin main"
    Then pi shows a native select dialog with options (force push / force-with-lease / cancel)
    And the options are generated by the model
    And picking an option runs the command the model generated for it

  Scenario: Force branch delete is gated
    When the model runs "git branch -D old-feature"
    Then pi shows a native select dialog with options (force delete / safe delete / cancel)

  Scenario: Hard reset and clean are gated
    When the model runs "git reset --hard" or "git clean -fd"
    Then pi shows a native select dialog with options including a safer alternative and cancel

  Scenario: Force worktree removal is gated
    When the model runs "git worktree remove .pi/worktrees/x --force"
    Then pi shows a native select dialog with options (force remove / remove only if clean / cancel)

  Scenario: Headless runs are blocked with a conversation reason
    Given no UI is available (pi -p / headless)
    When the model attempts a gated command
    Then the call is blocked
    And the reason instructs the model to ask the user in the conversation

  Scenario: Safe commands pass through
    When the model runs "git flow feature finish add-oauth-login"
    Then no dialog is shown and the call executes normally
