Feature: Risky GitHub operations require confirmation
  A tool_call hook gates irreversible GitHub operations (merging a PR,
  force-removing a worktree) with pi's native confirm dialog. The gate is
  not a tool — it registers no tool for the model — and cannot be skipped:
  it fires at tool-execution time and blocks the call unless the user
  confirms.

  Background:
    Given the @fradser/github package is installed
    And extensions/risky-gate.ts registers a tool_call hook (no registerTool)

  Scenario: PR merge is gated by an option dialog
    When the model runs "gh pr merge 123 --merge --delete-branch"
    Then pi shows a native select dialog with the merge options (merge commit / squash / rebase / cancel)
    And the options are generated by the model
    And picking an option runs the command the model generated for it
    And the call is blocked unless the user picks an option

  Scenario: Force worktree removal is gated
    When the model runs "git worktree remove .pi/worktrees/x --force"
    Then pi shows a native select dialog with options (force remove / remove only if clean / cancel)

  Scenario: Headless runs are blocked with a conversation reason
    Given no UI is available (pi -p / headless)
    When the model attempts a gated command
    Then the call is blocked
    And the reason instructs the model to ask the user in the conversation

  Scenario: Non-risky commands pass through
    When the model runs "gh pr view 123"
    Then no dialog is shown and the call executes normally
